version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: foa-testing
      POSTGRES_PASSWORD: foa123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foa-testing"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: minghao041216@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

  backend:
    container_name: backend
    image: jingxiang212/foa_village_backend:1.0
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    image: jingxiang212/foa_village_frontend:1.0
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
